### PR TITLE
replaced cogaps_result calls from the data folder with the .rds in th…

### PR DESCRIPTION
**Pull request by orian116**
…e inst/extdata folder. Also added corresponding documentation in inst/script.Package passed R CMD check and BiocCheck

### CODE REVIEW

**Comment by atuldeshpande** [comment]
Updated a couple files to pass length requirement. @orian116 can you check the indentations in the files?

**Comment by orian116** [comment]
@atuldeshpande and @dimalvovs I made a few changes in my most recent commit but it has conflicts that need to be resolved that's preventing me from creating a pull request. Could you guys check those out?

**Comment by dimalvovs** [comment]
@atuldeshpande all the builds have failed here (also locally), there is some bug that needs correction

**Review by dimalvovs — APPROVED** [review]
LGTM!
thanks for keeping the refactoring changes separate :)
while reviewing, I fixed the win builds as well - they were failing due to missing `mode="wb"` parameter in `download.file()`.

**Pull request merged**
